// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/payment_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "milestone3/be/internal/dto"
	entity "milestone3/be/internal/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPaymentRepository is a mock of PaymentRepository interface.
type MockPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepositoryMockRecorder
}

// MockPaymentRepositoryMockRecorder is the mock recorder for MockPaymentRepository.
type MockPaymentRepositoryMockRecorder struct {
	mock *MockPaymentRepository
}

// NewMockPaymentRepository creates a new mock instance.
func NewMockPaymentRepository(ctrl *gomock.Controller) *MockPaymentRepository {
	mock := &MockPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepository) EXPECT() *MockPaymentRepositoryMockRecorder {
	return m.recorder
}

// CheckPaymentStatusMidtrans mocks base method.
func (m *MockPaymentRepository) CheckPaymentStatusMidtrans(orderId string) (dto.CheckPaymentStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPaymentStatusMidtrans", orderId)
	ret0, _ := ret[0].(dto.CheckPaymentStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPaymentStatusMidtrans indicates an expected call of CheckPaymentStatusMidtrans.
func (mr *MockPaymentRepositoryMockRecorder) CheckPaymentStatusMidtrans(orderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPaymentStatusMidtrans", reflect.TypeOf((*MockPaymentRepository)(nil).CheckPaymentStatusMidtrans), orderId)
}

// Create mocks base method.
func (m *MockPaymentRepository) Create(payment *entity.Payment, orderId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", payment, orderId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPaymentRepositoryMockRecorder) Create(payment, orderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentRepository)(nil).Create), payment, orderId)
}

// CreateMidtrans mocks base method.
func (m *MockPaymentRepository) CreateMidtrans(payment entity.Payment, orderId string) (dto.PaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMidtrans", payment, orderId)
	ret0, _ := ret[0].(dto.PaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMidtrans indicates an expected call of CreateMidtrans.
func (mr *MockPaymentRepositoryMockRecorder) CreateMidtrans(payment, orderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMidtrans", reflect.TypeOf((*MockPaymentRepository)(nil).CreateMidtrans), payment, orderId)
}

// GetAll mocks base method.
func (m *MockPaymentRepository) GetAll() ([]entity.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]entity.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPaymentRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPaymentRepository)(nil).GetAll))
}

// GetById mocks base method.
func (m *MockPaymentRepository) GetById(id int) (entity.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(entity.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockPaymentRepositoryMockRecorder) GetById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockPaymentRepository)(nil).GetById), id)
}